[package]
name = "cucumber_rust"
version = "0.10.0"
edition = "2018"
resolver = "2"
description = """\
    Cucumber testing framework for Rust, with async support. \
    Fully native, no external test runners or dependencies.\
    """
license = "MIT OR Apache-2.0"
authors = [
    "Brendan Molloy <brendan@bbqsrc.net>",
    "Ilya Solovyiov <ilya.solovyiov@gmail.com>",
    "Kai Ren <tyranron@gmail.com>",
]
documentation = "https://docs.rs/cucumber_rust"
homepage = "https://github.com/bbqsrc/cucumber-rust"
repository = "https://github.com/bbqsrc/cucumber-rust"
readme = "README.md"
categories = ["asynchronous", "development-tools::testing"]
keywords = ["cucumber", "testing", "bdd", "atdd", "async"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["macros"]
macros = ["cucumber_rust_codegen", "inventory"]

[dependencies]
async-trait = "0.1.40"
atty = "0.2.14"
console = "0.14.1"
derive_more = { version = "0.99.16", features = ["deref", "display", "error", "from"], default_features = false }
either = "1.6"
futures = "0.3.17"
gherkin = { package = "gherkin_rust", version = "0.10" }
globwalk = "0.8"
itertools = "0.10"
linked-hash-map = "0.5"
regex = "1.5"
sealed = "0.3"

# "macros" feature dependencies
cucumber_rust_codegen = { version = "0.10", path = "./codegen", optional = true }
inventory = { version = "0.1.10", optional = true }

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "time"] }

[[test]]
name = "wait"
harness = false

[[test]]
name = "output"

[workspace]
members = ["codegen"]
exclude = ["book/tests"]
